// ============================================================
// Fully expanded ARM926EJ-S file list (auto-generated)
// Generated by expand_tbench.py
// ============================================================
//-P /home/ICer/work/ARM926EJS/ARM926EJS/verilog/modelgen/disass/RH_Linux_x86/pli.tab
//-load /home/ICer/work/ARM926EJS/ARM926EJS/verilog/modelgen/disass/RH_Linux_x86/disass.so

+libext+.v

// 打开 M_DDR_AXI 读写数据打印（matrix_top.v 里的监控段）；
// 需要看 DDR3 器件模型自己的 log 时，去掉本行并到 tbench_top.v 把 DEBUG 改回 1
+define+DDR_AXI_LOG

// ============================================================
// Include search paths
// ============================================================
+incdir+../ARM926EJS/ARM926EJS/verilog/MAIN_ARM926EJS
+incdir+../ARM926EJS/ARM926EJS/verilog/ARM9EJS
+incdir+../ARM926EJS/ARM926EJS/verilog/CP15
+incdir+../ARM926EJS/ARM926EJS/verilog/ETM9
+incdir+../ARM926EJS/ARM926EJS/verilog/tbenchfpga
+incdir+../ARM926EJS/ARM926EJS/verilog/TestChip
+incdir+../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/arm926fpga1
+incdir+../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2
+incdir+../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a
+incdir+../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/oscar
+incdir+/home/synopsys/syn/O-2018.06-SP1/dw/dw01/src_ver
+incdir+/home/synopsys/syn/O-2018.06-SP1/packages/gtech/src_ver
+incdir+../verilog/ddr3/model
// Xilinx 7-series 仿真原语 (DDR3 PHY: OSERDESE2/ISERDESE2/IDELAYE2/IDELAYCTRL/IOBUF...)
+incdir+/home/Xilinx/Vivado/2019.1/data/verilog/src/unisims
// ============================================================
// Files expanded from -y directories
// ============================================================
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffnrx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx4.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx5.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx6.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrnx8.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx4.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx5.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffrx8.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffsnx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffsnx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffsx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffsx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx11.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx12.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx20.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx22.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx4.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx5.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx6.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926dffx9.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx10.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx12.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx15.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx16.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx18.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx19.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx20.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx21.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx22.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx23.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx27.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx30.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx34.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx4.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx48.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx5.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx6.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx7.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx8.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrnx9.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx10.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx16.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx18.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx21.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx22.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx27.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx30.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx4.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx5.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx6.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx7.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffrx8.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsnx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsnx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsnx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsnx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffsx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx1.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx10.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx11.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx112.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx12.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx16.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx2.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx20.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx22.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx26.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx27.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx28.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx3.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx30.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx31.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx32.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx37.v
 -sv ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx38.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx4.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx5.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx56.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx7.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx75.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx77.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx8.v
 ../ARM926EJS/ARM926EJS/verilog/a926dffs/a926gdffx9.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/ARM9EJS.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsAGU.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsAU.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsArmShifter.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsCLZ.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsClkBlk.v
 -sv ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsConstants.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsCoreCtl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsCoreDP.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsDbg.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsDbgCommsctl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsDbgCommsdp.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsDbgctl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsDbgdp.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsDefs.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsExecute.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsFwd.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsICEctl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsICEdp.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsIMM.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsIPipe.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsISyncr.v
 -sv ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsJArrayBndChk.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsJDec.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsJInBuf.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsJNullPtr.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsJStack.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsLU.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsLogStatus.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsMASeq.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsMainSeq.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsMem.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsMulCtl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsMulDP.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsPSR.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsPipeCtl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsREG.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsRam3r2wSDff.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsRegBank.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsRegC.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsRegFwd.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsSat.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsSatTimes2.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsShALUADec.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsShALUCtl.v
-sv ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsShALUDefs.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsShALUSeq.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsShALUTDec.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsShifter.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsTapScanctl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsTapScandp.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsWRegDec.v
-sv  ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsWRegDecoder.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsWptctl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM9EJS/a9ejsWptdp.v
 ../ARM926EJS/ARM926EJS/verilog/TCM/PartialTestCell.v
 ../ARM926EJS/ARM926EJS/verilog/TCM/PartialTestCell18.v
 ../ARM926EJS/ARM926EJS/verilog/TCM/a926ejsTCM.v
 ../ARM926EJS/ARM926EJS/verilog/TCM/a926ejsTCMCtrl.v
 ../ARM926EJS/ARM926EJS/verilog/TCM/a926ejsTCMWB.v
 ../ARM926EJS/ARM926EJS/verilog/BIU/a926ejsBIU.v
 ../ARM926EJS/ARM926EJS/verilog/BIU/a926ejsDBIU.v
 ../ARM926EJS/ARM926EJS/verilog/BIU/a926ejsIBIU.v
 ../ARM926EJS/ARM926EJS/verilog/IExt/a926ejsIExt.v
 ../ARM926EJS/ARM926EJS/verilog/IExt/a926ejsIExtFifo.v
 ../ARM926EJS/ARM926EJS/verilog/DExt/a926ejsDExt.v
-sv  ../ARM926EJS/ARM926EJS/verilog/DExt/a926ejsDExtAddrFifo.v
 ../ARM926EJS/ARM926EJS/verilog/DExt/a926ejsDExtDataFifo.v
 ../ARM926EJS/ARM926EJS/verilog/DExt/a926ejsDExtWB.v
 ../ARM926EJS/ARM926EJS/verilog/ETMIF/a926ejsETMIF.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/DataRam128k.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/DirtyRam128k.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/TagRam128k.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/ValidRam128k.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheBiuIntf.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheDataIntf.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheDirtyIntf.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheEWB.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheFB.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CachePWB.v
-sv  ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheRGen.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheRamGasket.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheTagIntf.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheUTag.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926CacheValidIntf.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926DCache.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926DataCache.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926ICache.v
 ../ARM926EJS/ARM926EJS/verilog/Cache/a926InstrCache.v
 ../ARM926EJS/ARM926EJS/verilog/CP15/a926ejsCP15.v
 ../ARM926EJS/ARM926EJS/verilog/CP15/a926ejsCPctl.v
 ../ARM926EJS/ARM926EJS/verilog/CP15/a926ejsCPdp.v
-sv  ../ARM926EJS/ARM926EJS/verilog/CP15/a926ejsCPheader.v
 ../ARM926EJS/ARM926EJS/verilog/CP15/a926ejsCPjtag.v
 ../ARM926EJS/ARM926EJS/verilog/MMU/a926ejsMMU.v
 ../ARM926EJS/ARM926EJS/verilog/MMU/a926ejsMRAM.v
 ../ARM926EJS/ARM926EJS/verilog/MMU/a926ejsRAM.v
 ../ARM926EJS/ARM926EJS/verilog/MMU/a926ejsUTLB.v
 ../ARM926EJS/ARM926EJS/verilog/MMU/a926ejsUTLBentry.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/ETM9.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9AddrCompress.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9BufOut.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Control.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Defs-large.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Defs-medium.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Defs-small.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Fifo.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Jtag.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Sync.v
-sv  ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9Trace.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/Etm9TraceOut.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmAcaPipe.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmAddCmpAsy.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmAddrComp.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmBuffer.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmBufferRst1.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmCounter.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmDataComp.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmDefs.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmEventGen.v
-sv  ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmEventGenMux.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmFfEn.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmSequencer.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmTraceEn.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmTrigger.v
 ../ARM926EJS/ARM926EJS/verilog/ETM9/EtmViewData.v
 ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/tbench.v
 ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/EtmMonitor.v
// -v ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/LogDefs.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/TracePod.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/a926SignalScan.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/a926cpmonitor_fpga.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/a926debussy_fpga.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/armcmp.v
// ARM 的 tbenchfpga/glbl.v 只是空壳（GSR/GTS/PRLD 均为未驱动的 wire），
// 它的 GSR 靠 ARM 的 tbench.v 里 assign glbl.GSR 驱动；而本流程顶层是
// tbench_top，tbench 不会参与 elaborate，导致 GSR 悬空 (X)，
// 进而使 unisim 的 IDELAYE2/ISERDESE2 等无法工作（idelay_count = x）。
// 因此改用 Xilinx 标准 glbl（自带 GSR/GTS/PRLD 初始化）。
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/glbl.v
 ../verilog/glbl.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/vfp9CycleChecker.v
// ../ARM926EJS/ARM926EJS/verilog/tbenchfpga/vfp9Display.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/AHBTCMRoute.v
// ../ARM926EJS/ARM926EJS/verilog/TestChip/ARM926EJS_TC.v
// ../ARM926EJS/ARM926EJS/verilog/TestChip/ARM926EJS_TC_CORE.v
// ../ARM926EJS/ARM926EJS/verilog/TestChip/ARM926EJS_TC_MODULE.v
// ../ARM926EJS/ARM926EJS/verilog/TestChip/BScan.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/CLKINPAD.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/CLKOUTPAD.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/CoprocTBox.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/CoprocVal.v
-sv ../ARM926EJS/ARM926EJS/verilog/TestChip/EtmMuxDelay.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/EtmMuxDemux.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/ExtArbiter.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/INPAD.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/LockCheckA926EJS.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/MLAHB.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/MLAHBDecoder.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/OUTPAD.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/SRamArbiter.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/TCMGasket.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/TOUTPAD.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/TestLogic.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/VFPtbench.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/a9sClkGen.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/a9sMICE.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/a9sPLL.v
 ../ARM926EJS/ARM926EJS/verilog/TestChip/a9sSynch.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/arm926fpga1/BUFG.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/arm926fpga1/lmxcv_79a_fpga1.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/Ahb2AhbAsync.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/AhbDefaultSlave.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/AhbSdram2portAsync.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/AhbSdram2port_66B.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ApbMux3.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/Arbiter.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ClkRef.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/CmSpdMem.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ConfigInit.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/MuxM2S.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/MuxS2M.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/RandomAHBWrapper.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/SdramCtrl.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/SsramCtrl.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/TrickBox.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/Tube.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/build.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/cm9x6reset.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/fpgaconfig.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ics307.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ics307arbiter.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvAhbDecoder.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvAhbtoApb.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvIntC.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvRegs.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvSramctrl.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvSysAhbDecoder.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvSysAhbMux1S1M.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcv_79a_fpga2.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ltc1329.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/max146.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/memory.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/spd_dpram.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/writebuffer2port_66B.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/arm926fpga1/BUFG.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/arm926fpga1/lmxcv_79a_fpga1.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/emulator/lmxcv_79a_fpga1.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/Ahb2AhbAsync.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/AhbDefaultSlave.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/AhbSdram2portAsync.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/AhbSdram2port_66B.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ApbMux3.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/Arbiter.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ClkRef.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/CmSpdMem.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ConfigInit.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/MuxM2S.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/MuxS2M.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/RandomAHBWrapper.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/SdramCtrl.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/SsramCtrl.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/TrickBox.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/Tube.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/build.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/cm9x6reset.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/fpgaconfig.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ics307.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ics307arbiter.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvAhbDecoder.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvAhbtoApb.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvIntC.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvRegs.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvSramctrl.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvSysAhbDecoder.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcvSysAhbMux1S1M.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/lmxcv_79a_fpga2.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/ltc1329.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/max146.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/memory.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/spd_dpram.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/fpga2/writebuffer2port_66B.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/lmxcv3200_79a.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/oscar/OSCaR.v
// ../ARM926EJS/ARM926EJS/verilog/lmxcv3200_79a/oscar/OSCaR.v

// ============================================================
// Original -v files
// ============================================================
 ../ARM926EJS/ARM926EJS/verilog/MAIN_ARM926EJS/ARM926EJS.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/ARM926EJSCore.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/ARM9EJSwrap.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsClkBlk.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsClkGate.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsDRoute.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsIRoute.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsFCSE.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsSysCtl.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/a926ejsSysDebug.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/dummy_buffer.v
 ../ARM926EJS/ARM926EJS/verilog/ARM926EJS/TestWrapper.v

// ============================================================
// Content expanded from -f files
// ============================================================
-y /home/synopsys/syn/O-2018.06-SP1/dw/dw01/src_ver
//-y /home/ICer/work/RAM
/home/ICer/work/RAM/RAM1_1024x32BWm8.v
/home/ICer/work/RAM/RAM1_128x22.v
/home/ICer/work/RAM/RAM1_128x8bW.v
/home/ICer/work/RAM/RAM1_256x22.v
/home/ICer/work/RAM/RAM1_32x24.v
/home/ICer/work/RAM/RAM1_32x26.v
/home/ICer/work/RAM/RAM1_32x30.v

// ============================================================
// End of file
// ============================================================
/home/synopsys/syn/O-2018.06-SP1/packages/gtech/src_ver/GTECH_MUX2.v
/home/synopsys/syn/O-2018.06-SP1/packages/gtech/src_ver/GTECH_ADD_ABC.v
/home/synopsys/syn/O-2018.06-SP1/packages/gtech/src_ver/GTECH_ADD_AB.v
/home/synopsys/syn/O-2018.06-SP1/packages/gtech/src_ver/GTECH_UDP_MUX2.v
/home/ICer/work/ARM926EJS/ARM926EJS/verilog/modelgen/disass/RH_Linux_x86/disass.v
//../verilog/ahb_rom.v
//../verilog/ahb_bus_matrix.v
//../verilog/ahb_slave_led.v
../verilog/ahb_led.v
//../verilog/ahb_slave_sram.v
../verilog/ahb_sram_ctrl.v
//../verilog/data_ahb_top.v
// ---- APB 外设子系统 (AHB->APB 桥 + LED/TIMER/UART) ----
../verilog/ahb2apb.v
../verilog/apb_bus.v
../verilog/apb_led.v
../verilog/apb_timer.v
../verilog/apb_uart.v
../verilog/rom/rom_16KX32.v
../verilog/ram/RAM1_16Kx32B.v
../verilog/matrix_top.v
../verilog/soc_top.v
../test_arm/tbench_top.v

///home/ICer/work/vivado/ahb_matrix/ahb_matrix.ip_user_files/bd/ahb_axi_matrix/sim/ahb_axi_matrix.v
///home/ICer/work/vivado/ahb_matrix/ahb_matrix.srcs/sources_1/bd/ahb_axi_matrix/hdl/ahb_axi_matrix_wrapper.v

/home/ICer/work/vivado/ahb_matrix/ahb_matrix.ip_user_files/bd/ahb_axi_matrix/ip/ahb_axi_matrix_axi_crossbar_0_0/sim/ahb_axi_matrix_axi_crossbar_0_0.v
/home/ICer/work/vivado/ahb_matrix/ahb_matrix.ip_user_files/bd/ahb_axi_matrix/sim/ahb_axi_matrix.v
/home/ICer/work/vivado/ahb_matrix/ahb_matrix.srcs/sources_1/bd/ahb_axi_matrix/hdl/ahb_axi_matrix_wrapper.v

// ============================================================
// DDR3 控制器 (AXI4 slave -> M_DDR_AXI)
// 放在 matrix BD 之后，避免 Micron 模型里的宏影响 crossbar
// ============================================================
../verilog/ddr3/ddr3_top.v
../verilog/ddr3/ddr3_axi_pmem.v
../verilog/ddr3/ddr3_axi_retime.v
../verilog/ddr3/ddr3_axi.v
../verilog/ddr3/ddr3_core.v
../verilog/ddr3/ddr3_dfi_seq.v
../verilog/ddr3/ddr3_dfi_phy.v
// Micron DDR3 x16 器件模型（含 2048Mb_ddr3_parameters.vh，放在最后）
../verilog/ddr3/model/ddr3.v

// ============================================================
// Xilinx unisim 原语库（按需自动解析）
// 注：glbl 见上（已改为 Xilinx 标准 glbl.v）
// ============================================================
-y /home/Xilinx/Vivado/2019.1/data/verilog/src/unisims

//../verilog/glbl.v
